language: R
sudo: required
r_packages: 
  # work around temporary travis + R 3.5 bug
  - devtools
  - covr
  - lwgeom
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos++-dev libgdal-dev libnode-dev
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
