# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
r_packages: 
  # work around temporary travis + R 3.5 bug
  - devtools 
  - covr
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'